"""Seed database with exercise progression data."""

from sqlalchemy.orm import Session
from .models import Exercise, ProgressionChain


PROGRESSIONS_DATA = [
    {
        "id": "pushup",
        "name": "Push-up Progression",
        "name_pl": "Progresja Pompek",
        "description": "Progress from wall push-ups to one-arm push-ups",
        "exercises": [
            {
                "id": "pushup_wall",
                "name": "Wall Push-ups",
                "name_pl": "Pompki od ściany",
                "description": "Stand facing a wall, place hands on wall at shoulder height, perform push-up motion.",
                "muscle_groups": ["chest", "triceps", "shoulders"],
                "difficulty": 1,
                "default_sets": 3,
                "default_reps": 15,
                "tips": ["Keep body straight from head to heels", "Hands slightly wider than shoulder-width"],
                "common_mistakes": ["Letting hips sag or stick out", "Not going through full range of motion"],
            },
            {
                "id": "pushup_incline",
                "name": "Incline Push-ups",
                "name_pl": "Pompki od blatu",
                "description": "Hands on elevated surface (counter, bench, stairs), perform push-up motion.",
                "muscle_groups": ["chest", "triceps", "shoulders"],
                "difficulty": 2,
                "default_sets": 3,
                "default_reps": 12,
                "tips": ["Lower the surface height as you get stronger", "Keep core tight throughout"],
                "common_mistakes": ["Surface too high (too easy) or too low (too hard)"],
            },
            {
                "id": "pushup_knee",
                "name": "Knee Push-ups",
                "name_pl": "Pompki na kolanach",
                "description": "Push-ups with knees on the ground instead of toes.",
                "muscle_groups": ["chest", "triceps", "shoulders"],
                "difficulty": 3,
                "default_sets": 3,
                "default_reps": 12,
                "tips": ["Keep body straight from knees to head", "Place a mat under knees for comfort"],
                "common_mistakes": ["Hips too high (piking)", "Not lowering chest close enough to ground"],
            },
            {
                "id": "pushup_full",
                "name": "Full Push-ups",
                "name_pl": "Pełne pompki",
                "description": "Standard push-up from toes with full body straight.",
                "muscle_groups": ["chest", "triceps", "shoulders", "core"],
                "difficulty": 5,
                "default_sets": 3,
                "default_reps": 10,
                "tips": ["Arms at 45-degree angle from body", "Lower until chest nearly touches ground"],
                "common_mistakes": ["Sagging hips", "Incomplete range of motion"],
            },
            {
                "id": "pushup_diamond",
                "name": "Diamond Push-ups",
                "name_pl": "Pompki diamentowe",
                "description": "Push-up with hands close together forming a diamond shape.",
                "muscle_groups": ["triceps", "chest", "shoulders"],
                "difficulty": 6,
                "default_sets": 3,
                "default_reps": 8,
                "tips": ["Index fingers and thumbs touch to form diamond", "Keep elbows close to body"],
                "common_mistakes": ["Hands too far apart", "Flaring elbows out"],
            },
            {
                "id": "pushup_archer",
                "name": "Archer Push-ups",
                "name_pl": "Pompki łucznika",
                "description": "Wide push-up where you shift weight to one arm while the other stays straight.",
                "muscle_groups": ["chest", "triceps", "shoulders", "core"],
                "difficulty": 7,
                "default_sets": 3,
                "default_reps": 6,
                "tips": ["Alternate sides each rep", "Keep straight arm locked"],
                "common_mistakes": ["Bending the extended arm", "Rotating torso too much"],
            },
            {
                "id": "pushup_onearm",
                "name": "One-arm Push-ups",
                "name_pl": "Pompki na jednej ręce",
                "description": "Push-up performed with only one arm while other is behind back.",
                "muscle_groups": ["chest", "triceps", "shoulders", "core"],
                "difficulty": 9,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Wider foot stance for balance", "Keep hips square to ground"],
                "common_mistakes": ["Rotating hips open", "Not going through full range of motion"],
            },
        ],
    },
    {
        "id": "squat",
        "name": "Squat Progression",
        "name_pl": "Progresja Przysiadów",
        "description": "Progress from assisted squats to pistol squats",
        "exercises": [
            {
                "id": "squat_assisted",
                "name": "Assisted Squats",
                "name_pl": "Przysiady z asekuracją",
                "description": "Hold onto a sturdy object for balance while squatting.",
                "muscle_groups": ["quadriceps", "glutes", "hamstrings"],
                "difficulty": 1,
                "default_sets": 3,
                "default_reps": 15,
                "tips": ["Use a doorframe, pole, or TRX straps", "Gradually reduce assistance"],
                "common_mistakes": ["Relying too much on arm support", "Knees caving inward"],
            },
            {
                "id": "squat_box",
                "name": "Box Squats",
                "name_pl": "Przysiady na skrzynię",
                "description": "Squat down to a box or chair, pause, then stand.",
                "muscle_groups": ["quadriceps", "glutes", "hamstrings"],
                "difficulty": 2,
                "default_sets": 3,
                "default_reps": 12,
                "tips": ["Touch the box but don't sit fully", "Lower box height as you progress"],
                "common_mistakes": ["Plopping onto the box", "Using momentum to stand up"],
            },
            {
                "id": "squat_full",
                "name": "Full Squats",
                "name_pl": "Pełne przysiady",
                "description": "Bodyweight squat with full depth.",
                "muscle_groups": ["quadriceps", "glutes", "hamstrings", "core"],
                "difficulty": 3,
                "default_sets": 3,
                "default_reps": 15,
                "tips": ["Feet shoulder-width apart", "Keep chest up and back straight"],
                "common_mistakes": ["Heels coming off ground", "Rounding lower back"],
            },
            {
                "id": "squat_close",
                "name": "Close Squats",
                "name_pl": "Przysiady wąskie",
                "description": "Squat with feet close together.",
                "muscle_groups": ["quadriceps", "glutes", "hamstrings"],
                "difficulty": 5,
                "default_sets": 3,
                "default_reps": 12,
                "tips": ["Feet touching or very close together", "Arms forward for balance"],
                "common_mistakes": ["Heels lifting off ground", "Falling backwards"],
            },
            {
                "id": "squat_bulgarian",
                "name": "Bulgarian Split Squats",
                "name_pl": "Bułgarskie przysiady",
                "description": "Single leg squat with rear foot elevated on bench.",
                "muscle_groups": ["quadriceps", "glutes", "hamstrings"],
                "difficulty": 6,
                "default_sets": 3,
                "default_reps": 8,
                "tips": ["Rear foot laces down on bench", "Keep torso upright"],
                "common_mistakes": ["Leaning too far forward"],
            },
            {
                "id": "squat_shrimp",
                "name": "Shrimp Squats",
                "name_pl": "Przysiady krewetka",
                "description": "Single leg squat holding rear foot behind you.",
                "muscle_groups": ["quadriceps", "glutes", "hamstrings", "core"],
                "difficulty": 7,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Hold rear foot with hand behind back", "Touch rear knee to ground"],
                "common_mistakes": ["Falling to the side"],
            },
            {
                "id": "squat_pistol",
                "name": "Pistol Squats",
                "name_pl": "Przysiady pistoletowe",
                "description": "Single leg squat with other leg extended straight in front.",
                "muscle_groups": ["quadriceps", "glutes", "hamstrings", "core"],
                "difficulty": 9,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Extend non-working leg straight ahead", "Arms forward for counterbalance"],
                "common_mistakes": ["Falling backwards", "Bending extended leg"],
            },
        ],
    },
    {
        "id": "pullup",
        "name": "Pull-up Progression",
        "name_pl": "Progresja Podciągnięć",
        "description": "Progress from dead hangs to advanced pull-ups",
        "exercises": [
            {
                "id": "pullup_deadhang",
                "name": "Dead Hang",
                "name_pl": "Martwy zwis",
                "description": "Hang from bar with straight arms to build grip strength.",
                "muscle_groups": ["back", "biceps"],
                "difficulty": 1,
                "default_sets": 3,
                "default_reps": 1,
                "default_hold_seconds": 30,
                "tips": ["Grip bar slightly wider than shoulder-width", "Build up to 60 second holds"],
                "common_mistakes": ["Not fully extending arms"],
            },
            {
                "id": "pullup_scapular",
                "name": "Scapular Pull-ups",
                "name_pl": "Podciągnięcia łopatkowe",
                "description": "From dead hang, retract shoulder blades without bending arms.",
                "muscle_groups": ["back"],
                "difficulty": 2,
                "default_sets": 3,
                "default_reps": 10,
                "tips": ["Keep arms straight throughout", "Focus on squeezing shoulder blades"],
                "common_mistakes": ["Bending the arms"],
            },
            {
                "id": "pullup_negative",
                "name": "Negative Pull-ups",
                "name_pl": "Negatywy podciągnięć",
                "description": "Jump to top position, lower yourself as slowly as possible.",
                "muscle_groups": ["back", "biceps"],
                "difficulty": 3,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Use a box to jump to top position", "Aim for 5-10 second descent"],
                "common_mistakes": ["Dropping too fast"],
            },
            {
                "id": "pullup_assisted",
                "name": "Assisted Pull-ups",
                "name_pl": "Podciągnięcia z asystą",
                "description": "Pull-ups with band assistance or partner help.",
                "muscle_groups": ["back", "biceps"],
                "difficulty": 4,
                "default_sets": 3,
                "default_reps": 8,
                "tips": ["Use thinner bands as you get stronger", "Full range of motion every rep"],
                "common_mistakes": ["Using too much assistance"],
            },
            {
                "id": "pullup_full",
                "name": "Pull-ups",
                "name_pl": "Podciągnięcia",
                "description": "Full pull-up from dead hang to chin over bar.",
                "muscle_groups": ["back", "biceps"],
                "difficulty": 5,
                "default_sets": 3,
                "default_reps": 8,
                "tips": ["Start from dead hang, chin over bar at top", "Control the descent"],
                "common_mistakes": ["Kipping or using momentum", "Chin not clearing the bar"],
            },
            {
                "id": "pullup_lsit",
                "name": "L-sit Pull-ups",
                "name_pl": "Podciągnięcia z L-sit",
                "description": "Pull-ups while holding legs extended in L-sit position.",
                "muscle_groups": ["back", "biceps", "core"],
                "difficulty": 7,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Keep legs parallel to ground", "Maintain core tension throughout"],
                "common_mistakes": ["Legs dropping during pull"],
            },
            {
                "id": "pullup_archer",
                "name": "Archer Pull-ups",
                "name_pl": "Podciągnięcia łucznika",
                "description": "Wide grip pull-up alternating to each side.",
                "muscle_groups": ["back", "biceps"],
                "difficulty": 8,
                "default_sets": 3,
                "default_reps": 4,
                "tips": ["Wide grip, pull to alternating sides", "Keep one arm straight as you pull"],
                "common_mistakes": ["Not extending the non-working arm fully"],
            },
        ],
    },
    {
        "id": "core",
        "name": "Core Progression",
        "name_pl": "Progresja Core",
        "description": "Progress from planks to advanced core exercises",
        "exercises": [
            {
                "id": "core_plank",
                "name": "Plank",
                "name_pl": "Deska (plank)",
                "description": "Hold push-up position with arms straight or on forearms.",
                "muscle_groups": ["core"],
                "difficulty": 1,
                "default_sets": 3,
                "default_reps": 1,
                "default_hold_seconds": 30,
                "tips": ["Body straight from head to heels", "Squeeze glutes and brace abs"],
                "common_mistakes": ["Hips sagging down", "Hips piking up"],
            },
            {
                "id": "core_side_plank",
                "name": "Side Plank",
                "name_pl": "Deska boczna",
                "description": "Hold body sideways supported on one forearm.",
                "muscle_groups": ["core"],
                "difficulty": 2,
                "default_sets": 3,
                "default_reps": 1,
                "default_hold_seconds": 30,
                "tips": ["Keep hips up and body straight", "Equal time on both sides"],
                "common_mistakes": ["Hips dropping"],
            },
            {
                "id": "core_knee_raise",
                "name": "Hanging Knee Raises",
                "name_pl": "Unoszenie kolan w zwisie",
                "description": "Hang from bar and raise knees toward chest.",
                "muscle_groups": ["core"],
                "difficulty": 3,
                "default_sets": 3,
                "default_reps": 10,
                "tips": ["Control the movement, no swinging", "Curl pelvis up at top"],
                "common_mistakes": ["Using momentum to swing legs"],
            },
            {
                "id": "core_leg_raise",
                "name": "Hanging Leg Raises",
                "name_pl": "Unoszenie prostych nóg w zwisie",
                "description": "Hang from bar and raise straight legs to horizontal.",
                "muscle_groups": ["core"],
                "difficulty": 5,
                "default_sets": 3,
                "default_reps": 8,
                "tips": ["Keep legs straight throughout", "Control the descent"],
                "common_mistakes": ["Bending knees", "Swinging for momentum"],
            },
            {
                "id": "core_toes_to_bar",
                "name": "Toes to Bar",
                "name_pl": "Palce do drążka",
                "description": "Hang from bar and raise straight legs to touch the bar.",
                "muscle_groups": ["core"],
                "difficulty": 6,
                "default_sets": 3,
                "default_reps": 6,
                "tips": ["Touch toes to bar between hands", "Keep legs straight"],
                "common_mistakes": ["Kipping excessively"],
            },
            {
                "id": "core_lsit",
                "name": "L-sit",
                "name_pl": "L-sit",
                "description": "Support body on parallel bars with legs extended straight.",
                "muscle_groups": ["core", "triceps"],
                "difficulty": 7,
                "default_sets": 3,
                "default_reps": 1,
                "default_hold_seconds": 15,
                "tips": ["Start on parallettes or dip bars", "Keep legs straight and parallel to ground"],
                "common_mistakes": ["Bending knees"],
            },
            {
                "id": "core_dragon_flag",
                "name": "Dragon Flag",
                "name_pl": "Flaga smoka",
                "description": "Lie on bench, grip behind head, raise body to vertical and lower with control.",
                "muscle_groups": ["core"],
                "difficulty": 9,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Body straight from shoulders to toes", "Control the descent"],
                "common_mistakes": ["Bending at hips", "Lowering too fast"],
            },
        ],
    },
    {
        "id": "dip",
        "name": "Dip Progression",
        "name_pl": "Progresja Dipów",
        "description": "Progress from bench dips to ring dips",
        "exercises": [
            {
                "id": "dip_bench",
                "name": "Bench Dips",
                "name_pl": "Dipy na ławce",
                "description": "Hands on bench behind you, lower body by bending arms.",
                "muscle_groups": ["triceps", "chest", "shoulders"],
                "difficulty": 1,
                "default_sets": 3,
                "default_reps": 12,
                "tips": ["Legs bent for easier, straight for harder", "Keep back close to bench"],
                "common_mistakes": ["Going too low (shoulder strain)"],
            },
            {
                "id": "dip_negative",
                "name": "Negative Dips",
                "name_pl": "Negatywy dipów",
                "description": "Jump to top of dip position, lower yourself slowly.",
                "muscle_groups": ["triceps", "chest", "shoulders"],
                "difficulty": 3,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Lower for 5-10 seconds", "Control the entire movement"],
                "common_mistakes": ["Lowering too fast"],
            },
            {
                "id": "dip_assisted",
                "name": "Assisted Dips",
                "name_pl": "Dipy z asystą",
                "description": "Dips with band assistance.",
                "muscle_groups": ["triceps", "chest", "shoulders"],
                "difficulty": 4,
                "default_sets": 3,
                "default_reps": 8,
                "tips": ["Loop band under knees", "Use thinner bands as you progress"],
                "common_mistakes": ["Relying too much on band"],
            },
            {
                "id": "dip_parallel",
                "name": "Parallel Bar Dips",
                "name_pl": "Dipy na poręczach",
                "description": "Full dips on parallel bars.",
                "muscle_groups": ["triceps", "chest", "shoulders"],
                "difficulty": 5,
                "default_sets": 3,
                "default_reps": 8,
                "tips": ["Lean forward slightly for chest emphasis", "Stay upright for tricep emphasis"],
                "common_mistakes": ["Going too low (shoulder strain)"],
            },
            {
                "id": "dip_ring",
                "name": "Ring Dips",
                "name_pl": "Dipy na kółkach",
                "description": "Dips on gymnastics rings for added instability.",
                "muscle_groups": ["triceps", "chest", "shoulders", "core"],
                "difficulty": 7,
                "default_sets": 3,
                "default_reps": 6,
                "tips": ["Turn rings out at top (RTO)", "Keep rings close to body"],
                "common_mistakes": ["Rings swinging or flaring out"],
            },
            {
                "id": "dip_weighted",
                "name": "Weighted Dips",
                "name_pl": "Dipy z obciążeniem",
                "description": "Dips with added weight.",
                "muscle_groups": ["triceps", "chest", "shoulders"],
                "difficulty": 8,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Start with small weights", "Maintain perfect form despite weight"],
                "common_mistakes": ["Adding too much weight too fast"],
            },
        ],
    },
    {
        "id": "row",
        "name": "Row Progression",
        "name_pl": "Progresja Wiosłowania",
        "description": "Progress from incline rows to one-arm rows",
        "exercises": [
            {
                "id": "row_incline",
                "name": "Incline Rows",
                "name_pl": "Wiosłowanie pod kątem",
                "description": "Rows on bar set at high position (body more upright).",
                "muscle_groups": ["back", "biceps"],
                "difficulty": 1,
                "default_sets": 3,
                "default_reps": 15,
                "tips": ["Body straight from head to heels", "Pull chest to bar"],
                "common_mistakes": ["Sagging hips"],
            },
            {
                "id": "row_horizontal",
                "name": "Horizontal Rows",
                "name_pl": "Wiosłowanie poziome",
                "description": "Body horizontal under bar, pull chest to bar.",
                "muscle_groups": ["back", "biceps", "core"],
                "difficulty": 3,
                "default_sets": 3,
                "default_reps": 12,
                "tips": ["Body parallel to ground", "Squeeze shoulder blades at top"],
                "common_mistakes": ["Hips sagging"],
            },
            {
                "id": "row_wide",
                "name": "Wide Rows",
                "name_pl": "Wiosłowanie szerokim chwytem",
                "description": "Horizontal rows with wide grip.",
                "muscle_groups": ["back", "biceps"],
                "difficulty": 4,
                "default_sets": 3,
                "default_reps": 10,
                "tips": ["Grip 1.5x shoulder width", "Focus on squeezing back muscles"],
                "common_mistakes": ["Using arms instead of back"],
            },
            {
                "id": "row_feet_elevated",
                "name": "Feet Elevated Rows",
                "name_pl": "Wiosłowanie z nogami na podwyższeniu",
                "description": "Horizontal rows with feet elevated for increased difficulty.",
                "muscle_groups": ["back", "biceps", "core"],
                "difficulty": 5,
                "default_sets": 3,
                "default_reps": 10,
                "tips": ["Elevate feet on box or bench", "Full range of motion"],
                "common_mistakes": ["Hips dropping"],
            },
            {
                "id": "row_archer",
                "name": "Archer Rows",
                "name_pl": "Wiosłowanie łucznika",
                "description": "Wide row pulling to one side while other arm stays straight.",
                "muscle_groups": ["back", "biceps"],
                "difficulty": 6,
                "default_sets": 3,
                "default_reps": 6,
                "tips": ["Alternate sides", "Keep non-working arm straight"],
                "common_mistakes": ["Bending the extended arm"],
            },
            {
                "id": "row_onearm",
                "name": "One-arm Rows",
                "name_pl": "Wiosłowanie na jednej ręce",
                "description": "Horizontal row using only one arm.",
                "muscle_groups": ["back", "biceps", "core"],
                "difficulty": 7,
                "default_sets": 3,
                "default_reps": 5,
                "tips": ["Wider foot stance for stability", "Keep hips square to ground"],
                "common_mistakes": ["Rotating hips open"],
            },
        ],
    },
]


def seed_database(db: Session) -> None:
    """Seed database with exercise progressions."""
    # Check if already seeded
    existing = db.query(ProgressionChain).first()
    if existing:
        return

    for chain_data in PROGRESSIONS_DATA:
        chain = ProgressionChain(
            id=chain_data["id"],
            name=chain_data["name"],
            name_pl=chain_data.get("name_pl"),
            description=chain_data.get("description"),
        )
        db.add(chain)

        for order, ex_data in enumerate(chain_data["exercises"]):
            exercise = Exercise(
                id=ex_data["id"],
                name=ex_data["name"],
                name_pl=ex_data.get("name_pl"),
                description=ex_data.get("description"),
                difficulty=ex_data.get("difficulty", 1),
                chain_id=chain_data["id"],
                progression_order=order,
                default_sets=ex_data.get("default_sets", 3),
                default_reps=ex_data.get("default_reps", 10),
                default_hold_seconds=ex_data.get("default_hold_seconds"),
                muscle_groups=ex_data.get("muscle_groups", []),
                tips=ex_data.get("tips", []),
                common_mistakes=ex_data.get("common_mistakes", []),
            )
            db.add(exercise)

    db.commit()
